name: Build

on:
  push:
    branches: [ "main" ]

env:
  THIS_REPO_PATH: repo
  BUILD_DIR: _build

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Set up gcc 10
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 lcov cmake
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10

    - name: Install dependencies
      run: sudo apt-get install -y libudev-dev libv4l-dev libturbojpeg0-dev libcurl4-openssl-dev libssl-dev

    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        # repository: ${{ github.repository }}
        path: ${{ env.THIS_REPO_PATH }}

    - name: Set up Conan
      run: |
        pip install conan==1.57.0
        conan --version
        conan remote add sby ${{ secrets.CONAN_SBY_SERVER_URL }}
        conan user -r sby ${{ secrets.CONAN_USER }} -p ${{ secrets.CONAN_PASSWORD }}
        conan remote disable conancenter
        conan remote list
        conan search -r sby
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Download build-wrapper
      env:
        BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
      run: |
        mkdir -p $HOME/.sonar
        curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
        unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/

        echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH

    - name: Create folders
      working-directory: ${{ github.workspace}}/${{ env.THIS_REPO_PATH }}
      run: |
        mkdir -p ${{ env.BUILD_DIR }}

    - name: Make
      working-directory: ${{ github.workspace}}/${{ env.THIS_REPO_PATH }}/${{ env.BUILD_DIR }}
      run: |
        conan user
        conan profile list
        conan profile show default
        cmake -DCMAKE_BUILD_TYPE=Debug \
        -Dscv_WARNINGS_AS_ERRORS=TRUE \
        -Dscv_ENABLE_COVERAGE=TRUE \
        -Dscv_ENABLE_CLANG_TIDY=FALSE \
        -Dscv_ENABLE_CPPCHECK=TRUE \
        -Dscv_ENABLE_SANITIZER_ADDRESS=FALSE \
        -Dscv_ENABLE_SANITIZER_LEAK=FALSE \
        -Dscv_ENABLE_SANITIZER_UNDEFINED=FALSE \
        -Dscv_ENABLE_SANITIZER_THREAD=FALSE \
        -Dscv_ENABLE_SANITIZER_MEMORY=FALSE \
        ..
        build-wrapper-linux-x86-64 --out-dir . make -j2

        nm -o src/CMakeFiles/server.dir/main.cpp.o | c++filt | grep boost::wrapexcept
        nm -o src/CMakeFiles/server.dir/main.cpp.o | c++filt | grep boost::wrapexcept | wc -l
